variables:
  CONTAINER_IMAGE: $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  SERVICE_NAME: bullish

build:
  tags:
    - ci
  script:
    - docker build 
      --tag $CONTAINER_IMAGE 
      --build-arg NPM_REGISTRY=https://registry.npm.taobao.org 
      --build-arg SERVICE_API=https://bullish-api.mxsyx.site 
      --build-arg NEXT_PUBLIC_MEMPOOL_URL=https://mempool.mxsyx.site .

deploy:
  stage: deploy
  tags:
    - ci
  script:
    - if [[ -z $(docker service ls --format="{{.Name}}" | grep -w ^$SERVICE_NAME\$) ]]; then
    - docker service create
      --name=$SERVICE_NAME
      --replicas=1
      --update-delay=10s
      --env=API=http://bullish-api
      --env=NEXT_PUBLIC_API=https://bullish-api.mxsyx.site
      --env=NEXT_PUBLIC_MEMPOOL_URL=https://mempool.mxsyx.site
      --label="traefik.enable=true"
      --label="traefik.docker.lbswarm=true"
      --label="traefik.http.routers.$SERVICE_NAME.rule=Host(\`$SERVICE_NAME.mxsyx.site\`)"
      --label="traefik.http.routers.$SERVICE_NAME.tls.certResolver=letsencrypt"
      --label="traefik.http.services.$SERVICE_NAME.loadbalancer.server.port=3000"
      --network=traefik_default
      $CONTAINER_IMAGE
    - else
    - docker service scale $SERVICE_NAME=2
    - docker service update --image $CONTAINER_IMAGE $SERVICE_NAME
    - docker service scale $SERVICE_NAME=1
    - fi
