FROM node:18.17.0-alpine

WORKDIR /app

ARG API
ARG NEXT_PUBLIC_API
ARG NEXT_PUBLIC_MEMPOOL_URL
ENV API=$API
ENV NEXT_PUBLIC_API=$NEXT_PUBLIC_API
ENV NEXT_PUBLIC_MEMPOOL_URL=$NEXT_PUBLIC_MEMPOOL_URL

RUN npm install -g pnpm@8.2.0

COPY package.json pnpm-lock.yaml ./
RUN pnpm i

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
